/*
 * File: app/store/patientenList.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Hurricane.store.patientenList', {
    extend: 'Ext.data.Store',

    requires: [
        'Hurricane.model.patientenList',
        'Ext.util.Sorter',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'patientenList',
            autoLoad: true,
            autoSync: true,
            model: 'Hurricane.model.patientenList',
            sorters: {
                property: 'lastname'
            },
            proxy: {
                type: 'ajax',
                url: 'resource/Libraries/Database/gridPatientenList.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});