/*
 * File: app/store/patientenList.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Hurricane.store.patientenList', {
    extend: 'Ext.data.Store',

    requires: [
        'Hurricane.model.patientenList',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 500,
            storeId: 'patientenList',
            autoLoad: true,
            autoSync: true,
            model: 'Hurricane.model.patientenList',
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onStoreBeforeLoad,
                    scope: me
                },
                beforesync: {
                    fn: me.onBufferedStoreBeforeSync,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onStoreBeforeLoad: function(store, operation, eOpts) {
        var newURL = window.location.protocol + "//" + window.location.host;
        store.proxy.setUrl(newURL + '/resource/Libraries/Database/gridPatientenList.php');
    },

    onBufferedStoreBeforeSync: function(options, eOpts) {
        var newURL = window.location.protocol + "//" + window.location.host;
        store.proxy.setUrl(newURL + '/resource/Libraries/Database/gridPatientenList.php');
    }

});