/*
 * File: app/view/Eingabe.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Hurricane.view.Eingabe', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.eingabe',

    requires: [
        'Hurricane.view.EingabeViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'eingabe'
    },
    border: false,
    id: 'eingabe',
    frameHeader: false,
    header: false,
    title: 'My Panel',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'gridpanel',
            border: false,
            width: 300,
            frameHeader: false,
            header: false,
            title: 'My Grid Panel',
            store: 'patientenList',
            columns: [
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'patientenID',
                    text: 'Patienten Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'lastname',
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'count',
                    text: 'Anzahl'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Info'
                }
            ]
        }
    ]

});