/*
 * File: app/view/Eingabe.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Hurricane.view.Eingabe', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.eingabe',

    requires: [
        'Hurricane.view.EingabeViewModel',
        'Hurricane.view.EingabeViewController',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Template',
        'Ext.XTemplate',
        'Ext.grid.column.Action',
        'Ext.grid.plugin.BufferedRenderer'
    ],

    controller: 'eingabe',
    viewModel: {
        type: 'eingabe'
    },
    border: false,
    id: 'eingabe',
    frameHeader: false,
    header: false,
    title: 'My Panel',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'gridpanel',
            border: false,
            height: 500,
            id: 'patientenList',
            minHeight: 500,
            width: 300,
            frameHeader: false,
            header: false,
            manageHeight: false,
            title: 'My Grid Panel',
            store: 'patientenList',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 30
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'patientenID',
                    text: 'Patienten Id'
                },
                {
                    xtype: 'templatecolumn',
                    tpl: [
                        '<b>{lastname}, {firstname}</b><br />{gebDat:date("d.m.Y")}'
                    ],
                    width: 170,
                    dataIndex: 'lastname',
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    width: 50,
                    dataIndex: 'count',
                    text: 'Anzahl'
                },
                {
                    xtype: 'actioncolumn',
                    width: 50,
                    text: 'Info',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                Ext.create('Hurricane.view.DetailWindow', {record: record}).show();
                            },
                            icon: 'resource/icons/page_find.gif',
                            tooltip: 'Protocoll Info\'s'
                        }
                    ]
                }
            ],
            plugins: [
                {
                    ptype: 'bufferedrenderer',
                    leadingBufferZone: 50,
                    numFromEdge: 10,
                    trailingBufferZone: 50
                }
            ],
            listeners: {
                afterrender: 'onPatientenListAfterRender'
            }
        }
    ]

});