/*
 * File: app/view/frmEingabeViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Hurricane.view.frmEingabeViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.frmeingabe',

    onDatefieldFocus: function(component, event, eOpts) {
        Ext.getCmp('date').setValue(new Date());
    },

    onFirstnameIdKeyup: function(textfield, e, eOpts) {
        var store = Ext.getStore('patientenList') ;
        store.clearFilter(true);
        store.filter('lastname', Ext.getCmp('lastNameId').getValue(), true, false);
        store.filter('firstname', Ext.getCmp('firstnameId').getValue(), true, false);
        store.reload();
    },

    onLastNameIdKeyup: function(textfield, e, eOpts) {
        var store = Ext.getStore('patientenList') ;
        store.clearFilter(true);
        store.filter('lastname', Ext.getCmp('lastNameId').getValue(), true, false);
        store.filter('firstname', Ext.getCmp('firstnameId').getValue(), true, false);
        store.reload();

    },

    onButtonClick1: function(button, e, eOpts) {
        var form = Ext.getCmp('frmEingabe');
        if (form.isValid()) {
            form.submit({
                url: 'resource/Libraries/Database/savePatient.php',
                success: function (form, action){
                    Ext.Msg.show({
                        title: 'Speichern erfolgreich',
                        msg: 'Datensatz wurde erfolgreich gespeichert',
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.INFO
                    });
                    form.reset();
                    Ext.getStore('patientenList').reload();

                },
                failure: function(form, action) {
                    console.log(form);
                    console.log(action.result);
                    Ext.Msg.show({
                        title: 'Speichern fehlgeschlagen',
                        msg: 'Datensatz wurde nicht gespeichert <br>' + action.result,
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.ERROR
                    });
                },
            });

        }

        console.log(this);
    },

    onButtonClick: function(button, e, eOpts) {
        Ext.getCmp('frmEingabe').reset();
        Ext.getStore('PatientenList').clearFilter();
        Ext.getCmp('date').focus(false, 200);
    }

});
