/*
 * File: app/view/frmEingabe.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Hurricane.view.frmEingabe', {
    extend: 'Ext.form.Panel',
    alias: 'widget.frmeingabe',

    requires: [
        'Hurricane.view.frmEingabeViewModel',
        'Hurricane.view.frmEingabeViewController',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.form.field.TextArea',
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    controller: 'frmeingabe',
    viewModel: {
        type: 'frmeingabe'
    },
    height: 680,
    id: 'frmEingabe',
    width: 400,
    bodyPadding: 10,
    frameHeader: false,
    header: false,
    title: 'My Form',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'fieldset',
            height: 679,
            width: 406,
            title: 'My Fields',
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Info',
                    items: [
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            id: 'date',
                            fieldLabel: 'Datum',
                            name: 'Date',
                            format: 'd.m.Y',
                            submitFormat: 'Y-m-d',
                            listeners: {
                                focus: 'onDatefieldFocus'
                            }
                        },
                        {
                            xtype: 'timefield',
                            anchor: '100%',
                            fieldLabel: 'Uhrzeit',
                            name: 'intime',
                            allowBlank: false,
                            format: 'H:i',
                            submitFormat: 'H:i:s'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Patienten-Nr',
                            name: 'PatNr',
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Aufnahmeort',
                            name: 'shooting',
                            autoSelect: false,
                            displayField: 'key',
                            forceSelection: true,
                            minChars: 1,
                            store: 'Shooting',
                            typeAhead: true,
                            valueField: 'shootingID'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    title: 'Patienten Info',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'firstnameId',
                            fieldLabel: 'Vorname',
                            name: 'firstname',
                            enableKeyEvents: true,
                            listeners: {
                                keyup: 'onFirstnameIdKeyup'
                            }
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'lastNameId',
                            fieldLabel: 'Nachname',
                            name: 'lastname',
                            enableKeyEvents: true,
                            listeners: {
                                keyup: 'onLastNameIdKeyup'
                            }
                        },
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            fieldLabel: 'Geburtsdatum',
                            name: 'gebDat',
                            format: 'd.m.Y',
                            submitFormat: 'Y-m-d'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Geschlecht',
                            name: 'gender',
                            displayField: 'key',
                            forceSelection: true,
                            minChars: 2,
                            store: 'Gender',
                            typeAhead: true,
                            typeAheadDelay: 100,
                            valueField: 'GenderID'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Straße',
                            name: 'street'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Postleizahl',
                            name: 'plz'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Ort',
                            name: 'town'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    title: 'Kategorie / Helfer',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Diagnoseschlüssel',
                            name: 'digkey',
                            displayField: 'key',
                            forceSelection: true,
                            minChars: 2,
                            store: 'DiagnostickKey',
                            typeAhead: true,
                            typeAheadDelay: 100,
                            valueField: 'digID'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Verbleib',
                            name: 'whereabout',
                            displayField: 'key',
                            forceSelection: true,
                            minChars: 2,
                            store: 'Whereabout',
                            typeAhead: true,
                            typeAheadDelay: 100,
                            valueField: 'whereaboutID'
                        },
                        {
                            xtype: 'timefield',
                            anchor: '100%',
                            fieldLabel: 'Ausgangszeit',
                            name: 'outtime',
                            allowBlank: false,
                            format: 'H:i',
                            submitFormat: 'H:i:s'
                        },
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            fieldLabel: 'Ausgangsdatum',
                            name: 'outdate',
                            format: 'd.m.Y',
                            submitFormat: 'Y-m-d'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Bemerkung',
                            name: 'remark'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '1. Helfer-Nr',
                            name: 'helpernr1',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: '2. Helfer-Nr',
                            name: 'helpernr2'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    frameHeader: false,
                    header: false,
                    manageHeight: false,
                    title: 'My Panel',
                    layout: {
                        type: 'hbox',
                        align: 'middle',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Speichern',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '0 10 10 10 ',
                            text: 'Eingabe Löschen',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});