/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Hurricane.view.Main', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.main',

    requires: [
        'Hurricane.view.MainViewModel',
        'Hurricane.view.Eingabe',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.Img'
    ],

    viewModel: {
        type: 'main'
    },
    border: false,
    scrollable: true,
    layout: 'fit',
    header: false,
    title: 'My Panel',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'tabpanel',
            border: false,
            frameHeader: false,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    tabIndex: 1,
                    border: false,
                    layout: 'absolute',
                    title: 'Home',
                    tabConfig: {
                        xtype: 'tab',
                        closable: false
                    },
                    items: [
                        {
                            xtype: 'panel',
                            border: false,
                            frameHeader: false,
                            header: false,
                            manageHeight: false,
                            title: 'My Panel',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'image',
                                    margin: '70 0 0 0',
                                    width: 300,
                                    src: 'hurricane/2015/img/DRK640.png'
                                },
                                {
                                    xtype: 'image',
                                    margin: '50 0 0 0',
                                    src: 'hurricane/2015/img/hurricane2015.jpg'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    border: false,
                    title: 'Eingabe',
                    items: [
                        {
                            xtype: 'panel',
                            width: 300,
                            frameHeader: false,
                            header: false,
                            title: 'My Panel',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'eingabe',
                                    width: 300
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Tab 3'
                }
            ],
            listeners: {
                afterrender: 'onTabpanelAfterRender'
            }
        }
    ],

    onTabpanelAfterRender: function(component, eOpts) {
        //component.hideTabStripItem(0);
        console.log(component);
    }

});