/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Hurricane.view.Main', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.main',

    requires: [
        'Hurricane.view.MainViewModel',
        'Ext.Img',
        'Ext.form.field.Display'
    ],

    viewModel: {
        type: 'main'
    },
    height: 641,
    header: false,
    title: 'My Panel',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'image',
            margin: '70 0 0 0',
            width: 300,
            src: 'hurricane/2015/img/DRK640.png'
        },
        {
            xtype: 'image',
            margin: '50 0 0 0',
            src: 'hurricane/2015/img/hurricane2015.jpg'
        },
        {
            xtype: 'displayfield',
            flex: 1,
            margin: '60 0 0 0',
            style: {
                'font-size': '30px'
            },
            fieldLabel: 'Label',
            value: 'Patienten Registrierung 2015'
        }
    ]

});