/*
 * File: app/model/patientenList.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Hurricane.model.patientenList', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    idProperty: 'patientenList',

    fields: [
        {
            name: 'patientenID'
        },
        {
            name: 'firstname'
        },
        {
            name: 'lastname'
        },
        {
            name: 'street'
        },
        {
            name: 'plz'
        },
        {
            name: 'town'
        },
        {
            name: 'create_dat'
        },
        {
            name: 'change_dat'
        },
        {
            name: 'gebDat'
        },
        {
            name: 'genderID'
        },
        {
            name: 'count'
        }
    ]
});